## About Dataset
Context
This is a small subset of dataset of Book reviews from Amazon Kindle Store category.

Content
5-core dataset of product reviews from Amazon Kindle Store category from May 1996 - July 2014. Contains total of 982619 entries. Each reviewer has at least 5 reviews and each product has at least 5 reviews in this dataset.
Columns

- asin - ID of the product, like B000FA64PK
- helpful - helpfulness rating of the review - example: 2/3.
- overall - rating of the product.
- reviewText - text of the review (heading).
- reviewTime - time of the review (raw).
- reviewerID - ID of the reviewer, like A3SPTOKDG7WBLN
- reviewerName - name of the reviewer.
- summary - summary of the review (description).
- unixReviewTime - unix timestamp.

Acknowledgements
This dataset is taken from Amazon product data, Julian McAuley, UCSD website. http://jmcauley.ucsd.edu/data/amazon/

License to the data files belong to them.

Inspiration
- Sentiment analysis on reviews.
- Understanding how people rate usefulness of a review/ What factors influence helpfulness of a review.
- Fake reviews/ outliers.
- Best rated product IDs, or similarity between products based on reviews alone (not the best idea ikr).
- Any other interesting analysis

#### Best Practises
1. Preprocessing And Cleaning
2. Train Test Split
3. BOW,TFIDF,Word2vec
4. Train ML algorithms

In [1]:
# Load the dataset
import pandas as pd
data=pd.read_csv('Kindle Reviews/all_kindle_review.csv')
data.head()

,Unnamed: 0.1,Unnamed: 0,asin,helpful,rating,reviewText,reviewTime,reviewerID,reviewerName,summary,unixReviewTime
0,0,11539,B0033UV8HI,"[8, 10]",3,"Jace Rankin may be short, but he's nothing to ...","09 2, 2010",A3HHXRELK8BHQG,Ridley,Entertaining But Average,1283385600
1,1,5957,B002HJV4DE,"[1, 1]",5,Great short read. I didn't want to put it dow...,"10 8, 2013",A2RGNZ0TRF578I,Holly Butler,Terrific menage scenes!,1381190400
2,2,9146,B002ZG96I4,"[0, 0]",3,I'll start by saying this is the first of four...,"04 11, 2014",A3S0H2HV6U1I7F,Merissa,Snapdragon Alley,1397174400
3,3,7038,B002QHWOEU,"[1, 3]",3,Aggie is Angela Lansbury who carries pocketboo...,"07 5, 2014",AC4OQW3GZ919J,Cleargrace,very light murder cozy,1404518400
4,4,1776,B001A06VJ8,"[0, 1]",4,I did not expect this type of book to be in li...,"12 31, 2012",A3C9V987IQHOQD,Rjostler,Book,1356912000

In [2]:
df=data[['reviewText','rating']]
df.head()

                                          reviewText  rating
0  Jace Rankin may be short, but he's nothing to ...       3
1  Great short read.  I didn't want to put it dow...       5
2  I'll start by saying this is the first of four...       3
3  Aggie is Angela Lansbury who carries pocketboo...       3
4  I did not expect this type of book to be in li...       4

In [3]:
## Missing Values
df.isnull().sum()

reviewText    0
rating        0
dtype: int64

In [4]:
df['rating'].value_counts()

rating
5    3000
4    3000
3    2000
2    2000
1    2000
Name: count, dtype: int64

In [5]:
## postive review is 1 and negative review is 0
df['rating']=df['rating'].apply(lambda x:0 if x<4 else 1)

C:\Users\soumi\AppData\Local\Temp\ipykernel_10472\3099895650.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['rating']=df['rating'].apply(lambda x:0 if x<4 else 1)

In [6]:
df['rating'].value_counts()

rating
0    6000
1    6000
Name: count, dtype: int64

In [7]:
## 1. Lower All the cases
df['reviewText']=df['reviewText'].str.lower()

C:\Users\soumi\AppData\Local\Temp\ipykernel_10472\1654308119.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText']=df['reviewText'].str.lower()

In [8]:
df.head()

                                          reviewText  rating
0  jace rankin may be short, but he's nothing to ...       0
1  great short read.  i didn't want to put it dow...       1
2  i'll start by saying this is the first of four...       0
3  aggie is angela lansbury who carries pocketboo...       0
4  i did not expect this type of book to be in li...       1

In [9]:
import re
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\soumi\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [10]:
stop_words = set(stopwords.words('english'))

In [11]:
## Removing special characters
df['reviewText']=df['reviewText'].apply(lambda x:re.sub('[^a-z A-z 0-9-]+', '',x))
## Remove the stopswords
df['reviewText']=df['reviewText'].apply(lambda x:" ".join([y for y in x.split() if y not in stop_words]))
## Remove url 
df['reviewText']=df['reviewText'].apply(lambda x: re.sub(r'(http|https|ftp|ssh)://([\w_-]+(?:(?:\.[\w_-]+)+))([\w.,@?^=%&:/~+#-]*[\w@?^=%&/~+#-])?', '' , str(x)))
## Remove any additional spaces
df['reviewText']=df['reviewText'].apply(lambda x: " ".join(x.split()))

C:\Users\soumi\AppData\Local\Temp\ipykernel_10472\2195726171.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText']=df['reviewText'].apply(lambda x:re.sub('[^a-z A-z 0-9-]+', '',x))
C:\Users\soumi\AppData\Local\Temp\ipykernel_10472\2195726171.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText']=df['reviewText'].apply(lambda x:" ".join([y for y in x.split() if y not in stop_words]))
C:\Users\soumi\AppData\Local\Temp\ipykernel_10472\2195726171.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText']=df['reviewText'].apply(lambda x: re.sub(r'(http|https|ftp|ssh)://([\w_-]+(?:(?:\.[\w_-]+)+))([\w.,@?^=%&:/~+#-]*[\w@?^=%&/~+#-])?', '' , str(x)))
C:\Users\soumi\AppData\Local\Temp\ipykernel_10472\2195726171.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText']=df['reviewText'].apply(lambda x: " ".join(x.split()))

In [12]:
## Lemmatizer
from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()
def lemmatize_words(text):
    return " ".join([lemmatizer.lemmatize(word) for word in text.split()])

In [13]:
df['reviewText']=df['reviewText'].apply(lambda x:lemmatize_words(x))

C:\Users\soumi\AppData\Local\Temp\ipykernel_10472\1959687590.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText']=df['reviewText'].apply(lambda x:lemmatize_words(x))

In [14]:
## Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df['reviewText'],df['rating'],test_size=0.20)

In [15]:
from sklearn.feature_extraction.text import CountVectorizer
bow=CountVectorizer()
X_train_bow=bow.fit_transform(X_train).toarray()
X_test_bow=bow.transform(X_test).toarray()

In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()
X_train_tfidf=tfidf.fit_transform(X_train).toarray()
X_test_tfidf=tfidf.transform(X_test).toarray()

In [17]:
from sklearn.naive_bayes import GaussianNB
nb_model_bow=GaussianNB().fit(X_train_bow,y_train)
nb_model_tfidf=GaussianNB().fit(X_train_tfidf,y_train)

In [18]:
y_pred_bow=nb_model_bow.predict(X_test_bow)
y_pred_tfidf=nb_model_tfidf.predict(X_test_tfidf)

In [19]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Confusion Matrix for Bag of Words")
print(confusion_matrix(y_test,y_pred_bow))
print("Classification Report for Bag of Words")
print(classification_report(y_test,y_pred_bow))

print("Confusion Matrix for TF-IDF")
print(confusion_matrix(y_test,y_pred_tfidf))
print("Classification Report for TF-IDF")
print(classification_report(y_test,y_pred_tfidf))

Confusion Matrix for Bag of Words
[[990 220]
 [708 482]]
Classification Report for Bag of Words
              precision    recall  f1-score   support

           0       0.58      0.82      0.68      1210
           1       0.69      0.41      0.51      1190

    accuracy                           0.61      2400
   macro avg       0.63      0.61      0.60      2400
weighted avg       0.63      0.61      0.60      2400

Confusion Matrix for TF-IDF
[[878 332]
 [532 658]]
Classification Report for TF-IDF
              precision    recall  f1-score   support

           0       0.62      0.73      0.67      1210
           1       0.66      0.55      0.60      1190

    accuracy                           0.64      2400
   macro avg       0.64      0.64      0.64      2400
weighted avg       0.64      0.64      0.64      2400

In [20]:
print("Accuracy for Bag of Words:",accuracy_score(y_test,y_pred_bow))
print("Accuracy for TF-IDF:",accuracy_score(y_test,y_pred_tfidf))

Accuracy for Bag of Words: 0.6133333333333333
Accuracy for TF-IDF: 0.64

In [21]:
import gensim 
from gensim.models import Word2Vec, keyedvectors

In [22]:
import gensim.downloader as api
w2v=api.load('word2vec-google-news-300')

In [29]:
sentences = df['reviewText'].apply(lambda x: x.split()).tolist()
type(sentences), type(sentences[0]), type(sentences[0][0])

(list, list, str)

In [31]:
import numpy as np

In [32]:
def avgWord2VEC(sentence):
    M = []
    for word in sentence:
        try:
            M.append(w2v[word])
        except:
            pass
    M = np.array(M)
    v = M.mean(axis=0)
    if type(v) != np.ndarray:
        return np.zeros(300)
    return v

In [38]:
X = np.array([avgWord2VEC(x) for x in sentences])

In [39]:
X.shape

(12000, 300)

In [40]:
X_train_word2vec, X_test_word2vec, y_train_word2vec, y_test_word2vec = train_test_split(X, df['rating'], test_size=0.20)

In [42]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=1000)
model.fit(X_train_word2vec, y_train_word2vec)
y_pred_word2vec = model.predict(X_test_word2vec)

In [43]:
print(accuracy_score(y_test_word2vec, y_pred_word2vec))
print(classification_report(y_test_word2vec, y_pred_word2vec))

0.7991666666666667
              precision    recall  f1-score   support

           0       0.80      0.80      0.80      1204
           1       0.80      0.79      0.80      1196

    accuracy                           0.80      2400
   macro avg       0.80      0.80      0.80      2400
weighted avg       0.80      0.80      0.80      2400