In [1]:
import numpy as np
import pandas as pd

## 🟠 Task 5: IPL Dataset Analysis

In [18]:
df = pd.read_csv("ipl/matches.csv")
df.head()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan

In [34]:
df2 = pd.read_csv("ipl/deliveries.csv")
df2.loc[0:20, "total_runs"]

0     1
1     0
2     1
3     0
4     0
5     0
6     1
7     0
8     4
9     4
10    6
11    4
12    0
13    0
14    0
15    1
16    4
17    1
18    0
19    5
20    6
Name: total_runs, dtype: int64

In [38]:
df2.ball.value_counts()
df2.head(5)

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN

In [21]:
df2.batsman_runs.value_counts()

batsman_runs
0    103940
1     96778
4     29850
2     16453
6     13051
3       783
5        65
Name: count, dtype: int64

In [ ]:
top_run_scorrer = df2.groupby("batter").batsman_runs.sum()
top_run_scorrer = top_run_scorrer.sort_values(ascending=False)

batter
V Kohli           8014
S Dhawan          6769
RG Sharma         6630
DA Warner         6567
SK Raina          5536
                  ...
JL Denly             0
ND Doshi             0
C Nanda              0
Yash Dayal           0
V Pratap Singh       0
Name: batsman_runs, Length: 673, dtype: int64

In [ ]:
bowls_played = df2["batter"].value_counts()
bowls_played

batter
V Kohli          6236
S Dhawan         5483
RG Sharma        5183
DA Warner        4849
SK Raina         4177
                 ...
U Kaul              1
NJ Rimmington       1
Yash Dayal          1
SZ Mulani           1
Mayank Dagar        1
Name: count, Length: 673, dtype: int64

In [46]:
best_strike_rate = top_run_scorrer/bowls_played * 100
best_strike_rate.sort_values(ascending=False)

batter
L Wood             300.000000
B Stanlake         250.000000
J Fraser-McGurk    220.000000
R Sai Kishore      216.666667
Umar Gul           205.263158
                      ...
Sunny Gupta          0.000000
Mayank Dagar         0.000000
ND Doshi             0.000000
Abdur Razzak         0.000000
U Kaul               0.000000
Length: 673, dtype: float64

In [50]:
sr = pd.DataFrame({
    "runs": top_run_scorrer,
    "balls" : bowls_played,
    "sr": best_strike_rate,
})

sr

                runs  balls          sr
batter
A Ashish Reddy   280    196  142.857143
A Badoni         634    505  125.544554
A Chandila         4      7   57.142857
A Chopra          53     75   70.666667
A Choudhary       25     20  125.000000
...              ...    ...         ...
Yashpal Singh     47     67   70.149254
Younis Khan        3      7   42.857143
Yudhvir Singh     22     16  137.500000
Yuvraj Singh    2754   2207  124.784776
Z Khan           117    141   82.978723

[673 rows x 3 columns]

In [53]:
sr_filtered = sr[sr['balls'] > 200]
sr_filtered

                 runs  balls          sr
batter
A Badoni          634    505  125.544554
A Mishra          381    440   86.590909
A Symonds         974    781  124.711908
AA Jhunjhunwala   217    218   99.541284
AB de Villiers   5181   3487  148.580442
...               ...    ...         ...
Y Nagar           285    271  105.166052
Y Venugopal Rao   985    865  113.872832
YBK Jaiswal      1607   1095  146.757991
YK Pathan        3222   2334  138.046272
Yuvraj Singh     2754   2207  124.784776

[210 rows x 3 columns]

In [55]:
sr_filtered = sr_filtered.sort_values(by="sr", ascending=False)
sr_filtered.head(15)

                runs  balls          sr
batter
PD Salt          653    385  169.610390
T Stubbs         405    239  169.456067
TM Head          772    458  168.558952
AD Russell      2488   1515  164.224422
H Klaasen        993    613  161.990212
TH David         659    417  158.033573
SP Narine       1534    984  155.894309
Shashank Singh   423    272  155.514706
N Pooran        1769   1143  154.768154
LS Livingstone   939    609  154.187192
Rashid Khan      545    355  153.521127
GJ Maxwell      2772   1842  150.488599
C Green          707    472  149.788136
CH Morris        618    413  149.636804
RM Patidar       799    534  149.625468

In [56]:
sr_filtered2 = sr_filtered[sr_filtered['runs'] > 3000]
sr_filtered2

                runs  balls          sr
batter
AB de Villiers  5181   3487  148.580442
RR Pant         3297   2296  143.597561
SA Yadav        3594   2522  142.505948
JC Buttler      3583   2519  142.238984
CH Gayle        4997   3516  142.121729
KA Pollard      3437   2447  140.457703
YK Pathan       3222   2334  138.046272
DA Warner       6567   4849  135.429986
SV Samson       4419   3270  135.137615
SR Watson       3880   2892  134.163209
F du Plessis    4571   3435  133.071325
MS Dhoni        5243   3947  132.835065
SK Raina        5536   4177  132.535312
Shubman Gill    3216   2432  132.236842
KD Karthik      4843   3687  131.353404
Q de Kock       3160   2410  131.120332
KL Rahul        4689   3578  131.050866
V Kohli         8014   6236  128.511867
RG Sharma       6630   5183  127.918194
RV Uthappa      4954   3927  126.152279
AT Rayudu       4348   3490  124.584527
S Dhawan        6769   5483  123.454313
SS Iyer         3131   2545  123.025540
AM Rahane       4642   3858  120.321410
G Gambhir       4217   3524  119.665153
MK Pandey       3859   3288  117.366180

In [69]:
wickets_valid = df2[~df2['dismissal_kind'].isin(['run out', 'retired hurt'])]
wickets = wickets_valid.groupby('bowler').is_wicket.sum()
wickets
wickets.sort_values(ascending=False)

bowler
YS Chahal         205
PP Chawla         192
DJ Bravo          183
B Kumar           181
SP Narine         180
                 ...
AUK Pathan          0
AC Voges            0
AA Kazi             0
VS Yeligati         0
Vivrant Sharma      0
Name: is_wicket, Length: 530, dtype: int64

In [77]:
df.head(
)

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bengaluru,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Punjab Kings,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Capitals,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bengaluru,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan

In [73]:
team_maps = {
    'Royal Challengers Bangalore': 'Royal Challengers Bengaluru',
    'Kings XI Punjab': 'Punjab Kings',
    'Delhi Daredevils': 'Delhi Capitals',
    'Rising Pune Supergiants': 'Rising Pune Supergiant'
}

In [95]:
df = df.replace(team_maps)
df = df.replace(team_maps)

In [96]:
team1 = df.groupby("team1").team1.count().sort_values(ascending=False)
team2 = df.groupby("team2").team1.count().sort_values(ascending=False)

played = (team1 + team2).sort_values(ascending=False)

In [97]:
wins = df.groupby('winner').winner.count().sort_values(ascending=False)
wins

winner
Mumbai Indians                 144
Chennai Super Kings            138
Kolkata Knight Riders          131
Royal Challengers Bengaluru    123
Delhi Capitals                 115
Punjab Kings                   112
Rajasthan Royals               112
Sunrisers Hyderabad             88
Deccan Chargers                 29
Gujarat Titans                  28
Lucknow Super Giants            24
Rising Pune Supergiant          15
Gujarat Lions                   13
Pune Warriors                   12
Kochi Tuskers Kerala             6
Name: winner, dtype: int64

In [98]:
winrate = wins/played*100
winrate.fillna(0)

Chennai Super Kings            57.983193
Deccan Chargers                38.666667
Delhi Capitals                 45.634921
Gujarat Lions                  43.333333
Gujarat Titans                 62.222222
Kochi Tuskers Kerala           42.857143
Kolkata Knight Riders          52.191235
Lucknow Super Giants           54.545455
Mumbai Indians                 55.172414
Pune Warriors                  26.086957
Punjab Kings                   45.528455
Rajasthan Royals               50.678733
Rising Pune Supergiant         50.000000
Royal Challengers Bengaluru    48.235294
Sunrisers Hyderabad            48.351648
dtype: float64

## 🟠 Task 6: Combine NumPy + Pandas

In [13]:
data = np.random.randn(100, 3)
df = pd.DataFrame(data, columns=['a', 'b', 'c'])
df

           a         b         c
0   0.137167  0.622156 -0.357187
1  -0.924834 -0.727861 -0.376487
2  -0.024459 -0.523234  0.121892
3   0.959147 -1.135180 -0.908106
4   0.732553  0.037251  0.593293
..       ...       ...       ...
95 -0.779468 -1.359545 -1.304124
96  0.588270  1.074738  0.325429
97  0.026026 -0.915856  0.957180
98 -1.251864  1.215658  0.505857
99 -1.622665  1.646542 -0.109434

[100 rows x 3 columns]

In [14]:
df.corr()

          a         b         c
a  1.000000  0.115704  0.059424
b  0.115704  1.000000 -0.001245
c  0.059424 -0.001245  1.000000

In [20]:
z_index = (df - df.mean())/ df.std()
z_index
outliers = df[(z_index.abs() > 3).any(axis=1)]
outliers

          a         b         c
19 -0.29704 -0.306815 -4.049353

In [21]:
Q1 = df.quantile(0.25)
Q3 = df.quantile(0.75)
IQR = Q3 - Q1
IQR

a    1.537701
b    1.488453
c    1.199093
dtype: float64

In [23]:
outliers_iqr = df[
    ((df < (Q1 - 1.5 * IQR)) | (df > (Q3 + 1.5 * IQR))).any(axis=1)
]
outliers_iqr

           a         b         c
6   1.095641  0.121116  2.668308
19 -0.297040 -0.306815 -4.049353

In [26]:
df.head(8)

          a         b         c
0  0.137167  0.622156 -0.357187
1 -0.924834 -0.727861 -0.376487
2 -0.024459 -0.523234  0.121892
3  0.959147 -1.135180 -0.908106
4  0.732553  0.037251  0.593293
5  1.809165  0.247779  0.544646
6  1.095641  0.121116  2.668308
7 -1.356498  1.269440 -1.164121