In [1]:
import numpy as np
import pandas as pd

In [2]:
d = {
    "one" : pd.Series(list(range(1,5)), index=["a", "b", "c", "d"]),
    "two" : pd.Series(list(range(5,9)), index=["a", "b", "c", "d"])
}

In [10]:
df = pd.DataFrame(d, columns=["one", "two"])
df

   one  two
a    1    5
b    2    6
c    3    7
d    4    8

In [11]:
df.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [12]:
df.columns

Index(['one', 'two'], dtype='object')

In [22]:
data = np.zeros((2,), dtype=[("A", "i4"), ("B", "f4"), ("C", "S10")])
data

array([(0, 0., b''), (0, 0., b'')],
      dtype=[('A', '<i4'), ('B', '<f4'), ('C', 'S10')])

In [23]:
data[:] = [(1, 2.0, "Hello"), (2, 3.0, "World")]
data

array([(1, 2., b'Hello'), (2, 3., b'World')],
      dtype=[('A', '<i4'), ('B', '<f4'), ('C', 'S10')])

In [28]:
pd.DataFrame(
    {
        ("a", "b"): {("A", "B"): 1, ("A", "C"): 2},
        ("a", "a"): {("A", "C"): 3, ("A", "B"): 4},
        ("a", "c"): {("A", "B"): 5, ("A", "C"): 6},
        ("b", "a"): {("A", "C"): 7, ("A", "B"): 8},
        ("b", "b"): {("A", "D"): 9, ("A", "B"): 10},
    }
)

       a              b
       b    a    c    a     b
A B  1.0  4.0  5.0  8.0  10.0
  C  2.0  3.0  6.0  7.0   NaN
  D  NaN  NaN  NaN  NaN   9.0

In [33]:
index = pd.date_range("1/1/2000", periods=8)

s = pd.Series(np.random.randn(5), index=["a", "b", "c", "d", "e"])

df = pd.DataFrame(np.random.randn(8, 3), index=index, columns=["A", "B", "C"])
df

                   A         B         C
2000-01-01  0.673582  0.278417  0.798240
2000-01-02 -0.153098 -0.659745 -0.240085
2000-01-03 -0.405040 -0.106373  0.571546
2000-01-04  1.692144  0.857109  0.673683
2000-01-05  0.192401 -0.079118 -0.981676
2000-01-06  0.117886  0.303792  0.008928
2000-01-07  0.406569  0.970743  0.114358
2000-01-08  1.165019  0.695794  0.077756